### ISSUE TITLE
Intel Edison Support

### ISSUE THREAD

**Issue by taigrr** [morphis/meta-snappy#11]
The intel edison isn't quite to morty yet, and the projects that support transisitioning are, although not dead, very slow.

Is there a way to get this layer to work on the current intel edison build?

**Comment by ttzeng** [comment]
Though the yocto image for Intel Edison is not updated to morty yet, the meta-snappy layer can be added to the [dizzy based Edison tree](http://diydrones.com/m/blogpost?id=705844%3ABlogPost%3A2337002) with minor modifications. In addition, this layer also works with the new yocto based [Intel REF-OS-IOS](https://github.com/01org/ref-os-iot). FYR.

**Comment by taigrr** [comment]
We've since moved off the Intel Edison platform, so I can no longer test the answer reliably. Thanks for the response, though @ttzeng!
