### ISSUE TITLE
/var/lib/snapd/lib/gl is empty

### ISSUE THREAD

**Issue by om26er** [morphis/meta-snappy#35]
With opengl interface connected, when I run `snap run --shell <my_opengl_connected_snap>`, it seems the `/var/lib/snapd/lib/gl` directory is empty. Is there some service that is missing in our Yocto packaging ?

**Comment by bboozzoo** [comment]
The directory is only populated with libraries coming form the host. Right now the only case when this happens is when nvidia drivers are in use and only the ones that match the globs listed here: https://github.com/snapcore/snapd/blob/master/cmd/snap-confine/mount-support-nvidia.c#L83
