### ISSUE TITLE
Doesn't build on morty branch

### ISSUE THREAD

**Issue by ghost** [morphis/meta-snappy#7]
Hi,

Based on the instructions the snapd recipe doesn't build on morty.
```
| configure: error: "cannot find the rst2man tool, install python-docutils or similar"
| WARNING: /data/poky/build/tmp/work/i586-poky-linux/snapd/2.23.5-r0/temp/run.do_configure.19295:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_configure (log file is located at /data/poky/build/tmp/work/i586-poky-linux/snapd/2.23.5-r0/temp/log.do_configure.19295)
ERROR: Task (/data/poky/meta-snappy/recipes-support/snapd/snapd_2.23.5.bb:do_configure) failed with exit code '1'
```

**Comment by uhofemei** [comment]
After adding a dependency on python3-docutils-native and an inherit on python3native the issue is that it tries to call rst2man.py in the host sysroot, which starts with #!/usr/bin/env python. This points to python 2.7. The recipe for python-docutils was obsoleted in favor of python3-docutils.bb.

**Comment by morphis** [comment]
Thanks for the report and the first investigation. I will take a look into this and see if I can come up with a fix.

**Comment by morphis** [comment]
I guess the reason why I didn't saw this in my builds was that I had rst2man installed on my build system.

**Comment by uhofemei** [comment]
I fixed it by patching rst2man.py in the python3-docutils package :-)

```
--- a/tools/rst2man.py  2009-08-18 11:39:39.000000000 -0700
+++ b/tmp/rst2man.py  2017-04-04 18:25:14.049467561 -0700
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3

 # Author:
 # Contact: grubert@users.sf.net
```

**Comment by morphis** [comment]
@uhofemei Hm, wondering how this works for other packages in Yocto then or if they simply don't generate any man pages? We could disable this here too.

**Comment by uhofemei** [comment]
I need to submit the patch to OE core morty as python3-docutils is used there.

**Comment by om26er** [comment]
I guess this issue is moot. We should mostly support dunfell (because LTS) and the latest stable one.
